# Generated by Django 3.2.9 on 2021-11-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=8)),
                ('convertion', models.CharField(max_length=8)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
