# Generated by Django 3.2.9 on 2021-11-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
