# Generated by Django 3.2.9 on 2021-11-15 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0002_alter_conversion_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversion',
            old_name='convertion',
            new_name='conversion',
        ),
    ]
